version: '3'

services:
  kyupad-backend:
    container_name: kyupad-backend
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: always
    ports:
      - 80:80
